version: "3"

services:
  db:
    container_name: setlist_mysql
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme123rootPLS
      MYSQL_DATABASE: setlisty
