version: "3"

services:
  db:
    container_name: setlist_mysql
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-log-bin
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ../.env

  compiler:
    container_name: setlist_compiler
    image: node:16-alpine3.14
    volumes:
      - ../:/app
    working_dir: /app
    command: yarn run watch-compile

  bot:
    depends_on: 
      - db
      - compiler
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "nodemon"]
      interval: 1s
    container_name: setlist_bot
    image: node:16-alpine3.14
    volumes:
      - ../:/app
    working_dir: /app
    command: yarn run watch-bot
    env_file:
      - ../.env

  scraper:
    depends_on:
      - db
      - bot
    container_name: setlist_scraper
    image: node:16-alpine3.14
    volumes:
      - ../:/app
    env_file:
      - ../.env
    working_dir: /app
    command: yarn run watch-schedule