name: Build

on:
  push:
    branches: [ master, ci_build ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13'

      - run: yarn install
      - run: yarn tsc

      - run: cp docker/{Dockerfile,run.sh} .

      - uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: setlisty:latest